// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpXhmqkJBnjpkX3Gd3vHP4cgXurnCCPWc',
    appId: '1:897922463900:web:1098cc7e74182c51d0d559',
    messagingSenderId: '897922463900',
    projectId: 'flutterlogin-6d1f9',
    authDomain: 'flutterlogin-6d1f9.firebaseapp.com',
    storageBucket: 'flutterlogin-6d1f9.appspot.com',
    measurementId: 'G-0EQN0WVGG7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBszIoHwuYzhY2YK8sVe1f40sovHNzaYEs',
    appId: '1:897922463900:android:489d762b8b04a688d0d559',
    messagingSenderId: '897922463900',
    projectId: 'flutterlogin-6d1f9',
    storageBucket: 'flutterlogin-6d1f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBWIDk91li-GDlUPN2ZPamw7rVnv1dD7nk',
    appId: '1:897922463900:ios:3bbb174f92290b6cd0d559',
    messagingSenderId: '897922463900',
    projectId: 'flutterlogin-6d1f9',
    storageBucket: 'flutterlogin-6d1f9.appspot.com',
    iosClientId: '897922463900-nlrr1onqonelqskcek1dtcm6j5apdttp.apps.googleusercontent.com',
    iosBundleId: 'com.example.googlelogin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBWIDk91li-GDlUPN2ZPamw7rVnv1dD7nk',
    appId: '1:897922463900:ios:3bbb174f92290b6cd0d559',
    messagingSenderId: '897922463900',
    projectId: 'flutterlogin-6d1f9',
    storageBucket: 'flutterlogin-6d1f9.appspot.com',
    iosClientId: '897922463900-nlrr1onqonelqskcek1dtcm6j5apdttp.apps.googleusercontent.com',
    iosBundleId: 'com.example.googlelogin',
  );
}
